/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek.pkg2.s3.q1;

import java.awt.Color;

/**
 *
 * @author Muhammad Ammar Fadhlan, umar abdullah Azzam
 */

public class Page extends javax.swing.JFrame {
    /**
     * Creates new form Page
     */
    public Page() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        A1 = new javax.swing.JTextField();
        A2 = new javax.swing.JTextField();
        A3 = new javax.swing.JTextField();
        A4 = new javax.swing.JTextField();
        A5 = new javax.swing.JTextField();
        A6 = new javax.swing.JTextField();
        A7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        B2 = new javax.swing.JRadioButton();
        B3 = new javax.swing.JRadioButton();
        B4 = new javax.swing.JRadioButton();
        B5 = new javax.swing.JRadioButton();
        B6 = new javax.swing.JRadioButton();
        B7 = new javax.swing.JRadioButton();
        B1 = new javax.swing.JRadioButton();
        Exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("KiloGram");

        jLabel2.setText("HektoGram");

        jLabel3.setText("DekaGram");

        jLabel5.setText("DesiGram");

        jLabel6.setText("CentiGram");

        jLabel7.setText("MiliGram");

        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        A1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A1KeyReleased(evt);
            }
        });

        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        A2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A2KeyReleased(evt);
            }
        });

        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        A3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A3KeyReleased(evt);
            }
        });

        A4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A4KeyReleased(evt);
            }
        });

        A5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A5KeyReleased(evt);
            }
        });

        A6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A6KeyReleased(evt);
            }
        });

        A7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                A7KeyReleased(evt);
            }
        });

        jLabel8.setText("Gram");

        buttonGroup1.add(B2);
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(B3);
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });

        buttonGroup1.add(B4);
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });

        buttonGroup1.add(B5);
        B5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B5MouseClicked(evt);
            }
        });

        buttonGroup1.add(B6);
        B6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B6MouseClicked(evt);
            }
        });

        buttonGroup1.add(B7);
        B7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B7MouseClicked(evt);
            }
        });

        buttonGroup1.add(B1);
        B1.setToolTipText("");
        B1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B1MouseClicked(evt);
            }
        });
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(A6)
                            .addComponent(A7, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B6)
                            .addComponent(B7)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(B2)))
                .addGap(0, 430, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(A1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(B4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(A5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(A6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(B6)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(A7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Exit)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A1ActionPerformed

    private void A1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A1KeyReleased
        // TODO add your handling code here:
        Kilogram(A1.getText());
    }//GEN-LAST:event_A1KeyReleased

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B2ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_B1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void A2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A2KeyReleased
        // TODO add your handling code here:
        HektoGram(A2.getText());
    }//GEN-LAST:event_A2KeyReleased

    private void A3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A3KeyReleased
        // TODO add your handling code here:
        DekaGram(A3.getText());
    }//GEN-LAST:event_A3KeyReleased

    private void A4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A4KeyReleased
        // TODO add your handling code here:
        Gram(A4.getText());
    }//GEN-LAST:event_A4KeyReleased

    private void A5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A5KeyReleased
        // TODO add your handling code here:
        DesiGram(A5.getText());
    }//GEN-LAST:event_A5KeyReleased

    private void A6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A6KeyReleased
        // TODO add your handling code here:
        CentiGram(A6.getText());
    }//GEN-LAST:event_A6KeyReleased

    private void A7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A7KeyReleased
        // TODO add your handling code here:
        MiliGram(A7.getText());
    }//GEN-LAST:event_A7KeyReleased

    private void B1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B1MouseClicked
        // TODO add your handling code here:
        selectB1();
    }//GEN-LAST:event_B1MouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        // TODO add your handling code here:
        selectB2();
    }//GEN-LAST:event_B2MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        // TODO add your handling code here:
        selectB3();
    }//GEN-LAST:event_B3MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        // TODO add your handling code here:
        selectB4();
    }//GEN-LAST:event_B4MouseClicked

    private void B5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B5MouseClicked
        // TODO add your handling code here:
        selectB5();
    }//GEN-LAST:event_B5MouseClicked

    private void B6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B6MouseClicked
        // TODO add your handling code here:
        selectB6();
    }//GEN-LAST:event_B6MouseClicked

    private void B7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B7MouseClicked
        // TODO add your handling code here:
        selectB7();
    }//GEN-LAST:event_B7MouseClicked

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        exit();
    }//GEN-LAST:event_ExitActionPerformed

    public void exit(){
    System.exit(0);    
    }
    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
     disabler();
    }//GEN-LAST:event_formWindowActivated
   //Disable:
    public  void disabler(){
    A1.disable();
    A2.disable();
    A3.disable();
    A4.disable();
    A5.disable();
    A6.disable();
    A7.disable();
    }
    
    public void Kilogram(String input){
        double a = Double.parseDouble(input);       
        double b = a*10;
        A2.setText(Double.toString(b)+" HG");
        double c = a*100;
        A3.setText(Double.toString(c)+" DKG");
        double d = a*1000;
        A4.setText(Double.toString(d)+" G");
        double e = a*10000;
        A5.setText(Double.toString(e)+"  DG");
        double f = a*100000;
        A6.setText(Double.toString(f)+" CG");
        double g = a*1000000;
        A7.setText(Double.toString(g)+" MG");
    }
    public void HektoGram(String input){
        double a = Double.parseDouble(input);       
        double b = a/10;
        A1.setText(Double.toString(b)+" KG");
        double c = a*10;
        A3.setText(Double.toString(c)+" DKG");
        double d = a*100;
        A4.setText(Double.toString(d)+" G");
        double e = a*1000;
        A5.setText(Double.toString(e)+" DG");
        double f = a*10000;
        A6.setText(Double.toString(f)+" CG");
        double g = a*100000;
        A7.setText(Double.toString(g)+" MG");
    }
    public void DekaGram(String input){
        double a = Double.parseDouble(input);       
        double b = a/10;
        A2.setText(Double.toString(b)+" HG");
        double c = a/100;
        A1.setText(Double.toString(c)+" KG");
        double d = a*10;
        A4.setText(Double.toString(d)+" G");
        double e = a*100;
        A5.setText(Double.toString(e)+" DG");
        double f = a*1000;
        A6.setText(Double.toString(f)+" CG");
        double g = a*10000;
        A7.setText(Double.toString(g)+" MG");
    }
    public void Gram(String input){
        double a = Double.parseDouble(input);       
        double b = a/100;
        A2.setText(Double.toString(b)+" HG");
        double c = a/10;
        A3.setText(Double.toString(c)+" DKG");
        double d = a/1000;
        A1.setText(Double.toString(d)+" KG");
        double e = a*10;
        A5.setText(Double.toString(e)+" DG");
        double f = a*100;
        A6.setText(Double.toString(f)+" CG");
        double g = a*1000;
        A7.setText(Double.toString(g)+" MG");
    }
    public void DesiGram(String input){
        double a = Double.parseDouble(input);       
        double b = a/1000;
        A2.setText(Double.toString(b)+" HG");
        double c = a/100;
        A3.setText(Double.toString(c)+" DKG");
        double d = a/10;
        A4.setText(Double.toString(d)+" G");
        double e = a/10000;
        A1.setText(Double.toString(e)+" KG");
        double f = a*10;
        A6.setText(Double.toString(f)+" CG");
        double g = a*100;
        A7.setText(Double.toString(g)+" MG");
    }
    public void CentiGram(String input){
        double a = Double.parseDouble(input);       
        double b = a/10000;
        A2.setText(Double.toString(b)+" HG");
        double c = a/1000;
        A3.setText(Double.toString(c)+" DKG");
        double d = a/100;
        A4.setText(Double.toString(d)+" G");
        double e = a/10;
        A5.setText(Double.toString(e)+" DG");
        double f = a/100000;
        A1.setText(Double.toString(f)+" KG");
        double g = a*10;
        A7.setText(Double.toString(g)+" MG");
    }
    public void MiliGram(String input){
        double a = Double.parseDouble(input);       
        double b = a/100000;
       A2.setText(Double.toString(b)+" HG");
        double c = a/10000;
        A3.setText(Double.toString(c)+" DKG");
        double d = a/1000;
        A4.setText(Double.toString(d)+" G");
        double e = a/100;
        A5.setText(Double.toString(e)+" DG");
        double f = a/10;
        A6.setText(Double.toString(f)+" CG");
        double g = a/1000000;
        A1.setText(Double.toString(g)+" KG");
   }
   public void selectB1(){
        A1.setText(null);
        A1.setEnabled(true);
        A2.setEnabled(false);
        A3.setEnabled(false);
        A4.setEnabled(false);
        A5.setEnabled(false);
        A6.setEnabled(false);
        A7.setEnabled(false);
   }
   public void selectB2(){
        A2.setText(null);
        A1.setEnabled(false);
        A2.setEnabled(true);
        A3.setEnabled(false);
        A4.setEnabled(false);
        A5.setEnabled(false);
        A6.setEnabled(false);
        A7.setEnabled(false);
   }
   public void selectB3(){
        A3.setText(null);
        A1.setEnabled(false);
        A2.setEnabled(false);
        A3.setEnabled(true);
        A4.setEnabled(false);
        A5.setEnabled(false);
        A6.setEnabled(false);
        A7.setEnabled(false);
   }
   public void selectB4(){
        A4.setText(null);
        A1.setEnabled(false);
        A2.setEnabled(false);
        A3.setEnabled(false);
        A4.setEnabled(true);
        A5.setEnabled(false);
        A6.setEnabled(false);
        A7.setEnabled(false);
   }
   public void selectB5(){
        A5.setText(null);
        A1.setEnabled(false);
        A2.setEnabled(false);
        A3.setEnabled(false);
        A4.setEnabled(false);
        A5.setEnabled(true);
        A6.setEnabled(false);
        A7.setEnabled(false);
   }
   public void selectB6(){
        A6.setText(null);
        A1.setEnabled(false);
        A2.setEnabled(false);
        A3.setEnabled(false);
        A4.setEnabled(false);
        A5.setEnabled(false);
        A6.setEnabled(true);
        A7.setEnabled(false);
   }
   public void selectB7(){
        A7.setText(null);
        A1.setEnabled(false);
        A2.setEnabled(false);
        A3.setEnabled(false);
        A4.setEnabled(false);
        A5.setEnabled(false);
        A6.setEnabled(false);
        A7.setEnabled(true);
   }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField A1;
    public javax.swing.JTextField A2;
    public javax.swing.JTextField A3;
    public javax.swing.JTextField A4;
    public javax.swing.JTextField A5;
    public javax.swing.JTextField A6;
    public javax.swing.JTextField A7;
    private javax.swing.JRadioButton B1;
    private javax.swing.JRadioButton B2;
    private javax.swing.JRadioButton B3;
    private javax.swing.JRadioButton B4;
    private javax.swing.JRadioButton B5;
    private javax.swing.JRadioButton B6;
    private javax.swing.JRadioButton B7;
    public javax.swing.JButton Exit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
